#![doc = "Peripheral access API for CW32F030 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 3;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn WDT();
    fn LVD();
    fn RTC();
    fn FLASHRAM();
    fn RCC();
    fn GPIOA();
    fn GPIOB();
    fn GPIOC();
    fn GPIOF();
    fn DMACH1();
    fn DMACH23();
    fn DMACH45();
    fn ADC();
    fn ATIM();
    fn VC1();
    fn VC2();
    fn GTIM1();
    fn GTIM2();
    fn GTIM3();
    fn GTIM4();
    fn BTIM1();
    fn BTIM2();
    fn BTIM3();
    fn I2C1();
    fn I2C2();
    fn SPI1();
    fn SPI2();
    fn UART1();
    fn UART2();
    fn UART3();
    fn AWT();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 31] = [
    Vector { _handler: WDT },
    Vector { _handler: LVD },
    Vector { _handler: RTC },
    Vector { _handler: FLASHRAM },
    Vector { _handler: RCC },
    Vector { _handler: GPIOA },
    Vector { _handler: GPIOB },
    Vector { _handler: GPIOC },
    Vector { _handler: GPIOF },
    Vector { _handler: DMACH1 },
    Vector { _handler: DMACH23 },
    Vector { _handler: DMACH45 },
    Vector { _handler: ADC },
    Vector { _handler: ATIM },
    Vector { _handler: VC1 },
    Vector { _handler: VC2 },
    Vector { _handler: GTIM1 },
    Vector { _handler: GTIM2 },
    Vector { _handler: GTIM3 },
    Vector { _handler: GTIM4 },
    Vector { _handler: BTIM1 },
    Vector { _handler: BTIM2 },
    Vector { _handler: BTIM3 },
    Vector { _handler: I2C1 },
    Vector { _handler: I2C2 },
    Vector { _handler: SPI1 },
    Vector { _handler: SPI2 },
    Vector { _handler: UART1 },
    Vector { _handler: UART2 },
    Vector { _handler: UART3 },
    Vector { _handler: AWT },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - Watch Dog Timer Interrupt"]
    WDT = 0,
    #[doc = "1 - Low Voltage Detect Interrupt"]
    LVD = 1,
    #[doc = "2 - Real Time Clock Interrupt"]
    RTC = 2,
    #[doc = "3 - Flash/RAM Interrupt"]
    FLASHRAM = 3,
    #[doc = "4 - RCC Interupt"]
    RCC = 4,
    #[doc = "5 - GPIOA Interrupt"]
    GPIOA = 5,
    #[doc = "6 - GPIOB Interrupt"]
    GPIOB = 6,
    #[doc = "7 - GPIOC Interrupt"]
    GPIOC = 7,
    #[doc = "8 - GPIOF Interrupt"]
    GPIOF = 8,
    #[doc = "9 - DMA Channel 1 Interrupt"]
    DMACH1 = 9,
    #[doc = "10 - DMA Channel 2/3 Interrupt"]
    DMACH23 = 10,
    #[doc = "11 - DMA Channel 2/3 Interrupt"]
    DMACH45 = 11,
    #[doc = "12 - ADC Interrupt"]
    ADC = 12,
    #[doc = "13 - Advanced Timer Interrupt"]
    ATIM = 13,
    #[doc = "14 - Voltage Comparator 1 Interrupt"]
    VC1 = 14,
    #[doc = "15 - Voltage Comparator 2 Interrupt"]
    VC2 = 15,
    #[doc = "16 - General Timer1 Interrupt"]
    GTIM1 = 16,
    #[doc = "17 - General Timer2 Interrupt"]
    GTIM2 = 17,
    #[doc = "18 - General Timer3 Interrupt"]
    GTIM3 = 18,
    #[doc = "19 - General Timer4 Interrupt"]
    GTIM4 = 19,
    #[doc = "20 - Base Timer1 Interrupt"]
    BTIM1 = 20,
    #[doc = "21 - Base Timer2 Interrupt"]
    BTIM2 = 21,
    #[doc = "22 - Base Timer3 Interrupt"]
    BTIM3 = 22,
    #[doc = "23 - I2C1 Interrupt"]
    I2C1 = 23,
    #[doc = "24 - I2C2 Interrput"]
    I2C2 = 24,
    #[doc = "25 - SPI1 Interrupt"]
    SPI1 = 25,
    #[doc = "26 - SPI2 Interrupt"]
    SPI2 = 26,
    #[doc = "27 - UART1 Interrupt"]
    UART1 = 27,
    #[doc = "28 - UART2 Interrupt"]
    UART2 = 28,
    #[doc = "29 - UART3 Interrupt"]
    UART3 = 29,
    #[doc = "30 - Auto Wakeup Timer Interrupt"]
    AWT = 30,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "desc ADC"]
pub type Adc = crate::Periph<adc::RegisterBlock, 0x4001_2400>;
impl core::fmt::Debug for Adc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc").finish()
    }
}
#[doc = "desc ADC"]
pub mod adc;
#[doc = "desc ATIM"]
pub type Atim = crate::Periph<atim::RegisterBlock, 0x4001_2c00>;
impl core::fmt::Debug for Atim {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Atim").finish()
    }
}
#[doc = "desc ATIM"]
pub mod atim;
#[doc = "desc AWT"]
pub type Awt = crate::Periph<awt::RegisterBlock, 0x4001_4c00>;
impl core::fmt::Debug for Awt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Awt").finish()
    }
}
#[doc = "desc AWT"]
pub mod awt;
#[doc = "Base Timer 1"]
pub type Btim1 = crate::Periph<btim1::RegisterBlock, 0x4001_4800>;
impl core::fmt::Debug for Btim1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Btim1").finish()
    }
}
#[doc = "Base Timer 1"]
pub mod btim1;
#[doc = "Base Timer 2"]
pub type Btim2 = crate::Periph<btim1::RegisterBlock, 0x4001_4900>;
impl core::fmt::Debug for Btim2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Btim2").finish()
    }
}
#[doc = "Base Timer 2"]
pub use self::btim1 as btim2;
#[doc = "Base Timer 3"]
pub type Btim3 = crate::Periph<btim1::RegisterBlock, 0x4001_4a00>;
impl core::fmt::Debug for Btim3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Btim3").finish()
    }
}
#[doc = "Base Timer 3"]
pub use self::btim1 as btim3;
#[doc = "desc CRC"]
pub type Crc = crate::Periph<crc::RegisterBlock, 0x4002_3000>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
#[doc = "desc CRC"]
pub mod crc;
#[doc = "desc DMA"]
pub type Dma = crate::Periph<dma::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for Dma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma").finish()
    }
}
#[doc = "desc DMA"]
pub mod dma;
#[doc = "DMA Channel 1"]
pub type Dmachannel1 = crate::Periph<dmachannel1::RegisterBlock, 0x4002_0020>;
impl core::fmt::Debug for Dmachannel1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmachannel1").finish()
    }
}
#[doc = "DMA Channel 1"]
pub mod dmachannel1;
#[doc = "DMA Channel 2"]
pub type Dmachannel2 = crate::Periph<dmachannel1::RegisterBlock, 0x4002_0040>;
impl core::fmt::Debug for Dmachannel2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmachannel2").finish()
    }
}
#[doc = "DMA Channel 2"]
pub use self::dmachannel1 as dmachannel2;
#[doc = "DMA Channel 3"]
pub type Dmachannel3 = crate::Periph<dmachannel1::RegisterBlock, 0x4002_0060>;
impl core::fmt::Debug for Dmachannel3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmachannel3").finish()
    }
}
#[doc = "DMA Channel 3"]
pub use self::dmachannel1 as dmachannel3;
#[doc = "DMA Channel 4"]
pub type Dmachannel4 = crate::Periph<dmachannel1::RegisterBlock, 0x4002_0080>;
impl core::fmt::Debug for Dmachannel4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmachannel4").finish()
    }
}
#[doc = "DMA Channel 4"]
pub use self::dmachannel1 as dmachannel4;
#[doc = "DMA Channel 5"]
pub type Dmachannel5 = crate::Periph<dmachannel1::RegisterBlock, 0x4002_00a0>;
impl core::fmt::Debug for Dmachannel5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmachannel5").finish()
    }
}
#[doc = "DMA Channel 5"]
pub use self::dmachannel1 as dmachannel5;
#[doc = "desc FLASH"]
pub type Flash = crate::Periph<flash::RegisterBlock, 0x4002_2000>;
impl core::fmt::Debug for Flash {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flash").finish()
    }
}
#[doc = "desc FLASH"]
pub mod flash;
#[doc = "desc GPIOA"]
pub type Gpioa = crate::Periph<gpioa::RegisterBlock, 0x4800_0000>;
impl core::fmt::Debug for Gpioa {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioa").finish()
    }
}
#[doc = "desc GPIOA"]
pub mod gpioa;
#[doc = "desc GPIOB"]
pub type Gpiob = crate::Periph<gpioa::RegisterBlock, 0x4800_0400>;
impl core::fmt::Debug for Gpiob {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiob").finish()
    }
}
#[doc = "desc GPIOB"]
pub use self::gpioa as gpiob;
#[doc = "desc GPIOC"]
pub type Gpioc = crate::Periph<gpioc::RegisterBlock, 0x4800_0800>;
impl core::fmt::Debug for Gpioc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioc").finish()
    }
}
#[doc = "desc GPIOC"]
pub mod gpioc;
#[doc = "desc GPIOF"]
pub type Gpiof = crate::Periph<gpiof::RegisterBlock, 0x4800_1400>;
impl core::fmt::Debug for Gpiof {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiof").finish()
    }
}
#[doc = "desc GPIOF"]
pub mod gpiof;
#[doc = "General Timer 1"]
pub type Gtim1 = crate::Periph<gtim1::RegisterBlock, 0x4000_0400>;
impl core::fmt::Debug for Gtim1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gtim1").finish()
    }
}
#[doc = "General Timer 1"]
pub mod gtim1;
#[doc = "General Timer 2"]
pub type Gtim2 = crate::Periph<gtim1::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Gtim2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gtim2").finish()
    }
}
#[doc = "General Timer 2"]
pub use self::gtim1 as gtim2;
#[doc = "General Timer 3"]
pub type Gtim3 = crate::Periph<gtim1::RegisterBlock, 0x4001_4000>;
impl core::fmt::Debug for Gtim3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gtim3").finish()
    }
}
#[doc = "General Timer 3"]
pub use self::gtim1 as gtim3;
#[doc = "General Timer 4"]
pub type Gtim4 = crate::Periph<gtim1::RegisterBlock, 0x4001_4400>;
impl core::fmt::Debug for Gtim4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gtim4").finish()
    }
}
#[doc = "General Timer 4"]
pub use self::gtim1 as gtim4;
#[doc = "desc I2C1"]
pub type I2c1 = crate::Periph<i2c1::RegisterBlock, 0x4000_5400>;
impl core::fmt::Debug for I2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1").finish()
    }
}
#[doc = "desc I2C1"]
pub mod i2c1;
#[doc = "desc I2C2"]
pub type I2c2 = crate::Periph<i2c1::RegisterBlock, 0x4000_5800>;
impl core::fmt::Debug for I2c2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c2").finish()
    }
}
#[doc = "desc I2C2"]
pub use self::i2c1 as i2c2;
#[doc = "desc IWDT"]
pub type Iwdt = crate::Periph<iwdt::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Iwdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Iwdt").finish()
    }
}
#[doc = "desc IWDT"]
pub mod iwdt;
#[doc = "desc LVD"]
pub type Lvd = crate::Periph<lvd::RegisterBlock, 0x4001_2a80>;
impl core::fmt::Debug for Lvd {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lvd").finish()
    }
}
#[doc = "desc LVD"]
pub mod lvd;
#[doc = "desc RAM"]
pub type Ram = crate::Periph<ram::RegisterBlock, 0x4002_2400>;
impl core::fmt::Debug for Ram {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ram").finish()
    }
}
#[doc = "desc RAM"]
pub mod ram;
#[doc = "desc RTC"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x4000_2800>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "desc RTC"]
pub mod rtc;
#[doc = "desc SPI1"]
pub type Spi1 = crate::Periph<spi1::RegisterBlock, 0x4001_3000>;
impl core::fmt::Debug for Spi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi1").finish()
    }
}
#[doc = "desc SPI1"]
pub mod spi1;
#[doc = "desc SPI2"]
pub type Spi2 = crate::Periph<spi1::RegisterBlock, 0x4000_3800>;
impl core::fmt::Debug for Spi2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi2").finish()
    }
}
#[doc = "desc SPI2"]
pub use self::spi1 as spi2;
#[doc = "System Ctrl"]
pub type Sysctrl = crate::Periph<sysctrl::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Sysctrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sysctrl").finish()
    }
}
#[doc = "System Ctrl"]
pub mod sysctrl;
#[doc = "desc UART1"]
pub type Uart1 = crate::Periph<uart1::RegisterBlock, 0x4001_3800>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
#[doc = "desc UART1"]
pub mod uart1;
#[doc = "desc UART2"]
pub type Uart2 = crate::Periph<uart1::RegisterBlock, 0x4000_4400>;
impl core::fmt::Debug for Uart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart2").finish()
    }
}
#[doc = "desc UART2"]
pub use self::uart1 as uart2;
#[doc = "desc UART3"]
pub type Uart3 = crate::Periph<uart1::RegisterBlock, 0x4000_4800>;
impl core::fmt::Debug for Uart3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart3").finish()
    }
}
#[doc = "desc UART3"]
pub use self::uart1 as uart3;
#[doc = "desc VC1"]
pub type Vc1 = crate::Periph<vc1::RegisterBlock, 0x4001_2a00>;
impl core::fmt::Debug for Vc1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Vc1").finish()
    }
}
#[doc = "desc VC1"]
pub mod vc1;
#[doc = "desc VC2"]
pub type Vc2 = crate::Periph<vc1::RegisterBlock, 0x4001_2a10>;
impl core::fmt::Debug for Vc2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Vc2").finish()
    }
}
#[doc = "desc VC2"]
pub use self::vc1 as vc2;
#[doc = "desc WWDT"]
pub type Wwdt = crate::Periph<wwdt::RegisterBlock, 0x4000_2c00>;
impl core::fmt::Debug for Wwdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wwdt").finish()
    }
}
#[doc = "desc WWDT"]
pub mod wwdt;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "ADC"]
    pub adc: Adc,
    #[doc = "ATIM"]
    pub atim: Atim,
    #[doc = "AWT"]
    pub awt: Awt,
    #[doc = "BTIM1"]
    pub btim1: Btim1,
    #[doc = "BTIM2"]
    pub btim2: Btim2,
    #[doc = "BTIM3"]
    pub btim3: Btim3,
    #[doc = "CRC"]
    pub crc: Crc,
    #[doc = "DMA"]
    pub dma: Dma,
    #[doc = "DMACHANNEL1"]
    pub dmachannel1: Dmachannel1,
    #[doc = "DMACHANNEL2"]
    pub dmachannel2: Dmachannel2,
    #[doc = "DMACHANNEL3"]
    pub dmachannel3: Dmachannel3,
    #[doc = "DMACHANNEL4"]
    pub dmachannel4: Dmachannel4,
    #[doc = "DMACHANNEL5"]
    pub dmachannel5: Dmachannel5,
    #[doc = "FLASH"]
    pub flash: Flash,
    #[doc = "GPIOA"]
    pub gpioa: Gpioa,
    #[doc = "GPIOB"]
    pub gpiob: Gpiob,
    #[doc = "GPIOC"]
    pub gpioc: Gpioc,
    #[doc = "GPIOF"]
    pub gpiof: Gpiof,
    #[doc = "GTIM1"]
    pub gtim1: Gtim1,
    #[doc = "GTIM2"]
    pub gtim2: Gtim2,
    #[doc = "GTIM3"]
    pub gtim3: Gtim3,
    #[doc = "GTIM4"]
    pub gtim4: Gtim4,
    #[doc = "I2C1"]
    pub i2c1: I2c1,
    #[doc = "I2C2"]
    pub i2c2: I2c2,
    #[doc = "IWDT"]
    pub iwdt: Iwdt,
    #[doc = "LVD"]
    pub lvd: Lvd,
    #[doc = "RAM"]
    pub ram: Ram,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "SPI1"]
    pub spi1: Spi1,
    #[doc = "SPI2"]
    pub spi2: Spi2,
    #[doc = "SYSCTRL"]
    pub sysctrl: Sysctrl,
    #[doc = "UART1"]
    pub uart1: Uart1,
    #[doc = "UART2"]
    pub uart2: Uart2,
    #[doc = "UART3"]
    pub uart3: Uart3,
    #[doc = "VC1"]
    pub vc1: Vc1,
    #[doc = "VC2"]
    pub vc2: Vc2,
    #[doc = "WWDT"]
    pub wwdt: Wwdt,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            adc: Adc::steal(),
            atim: Atim::steal(),
            awt: Awt::steal(),
            btim1: Btim1::steal(),
            btim2: Btim2::steal(),
            btim3: Btim3::steal(),
            crc: Crc::steal(),
            dma: Dma::steal(),
            dmachannel1: Dmachannel1::steal(),
            dmachannel2: Dmachannel2::steal(),
            dmachannel3: Dmachannel3::steal(),
            dmachannel4: Dmachannel4::steal(),
            dmachannel5: Dmachannel5::steal(),
            flash: Flash::steal(),
            gpioa: Gpioa::steal(),
            gpiob: Gpiob::steal(),
            gpioc: Gpioc::steal(),
            gpiof: Gpiof::steal(),
            gtim1: Gtim1::steal(),
            gtim2: Gtim2::steal(),
            gtim3: Gtim3::steal(),
            gtim4: Gtim4::steal(),
            i2c1: I2c1::steal(),
            i2c2: I2c2::steal(),
            iwdt: Iwdt::steal(),
            lvd: Lvd::steal(),
            ram: Ram::steal(),
            rtc: Rtc::steal(),
            spi1: Spi1::steal(),
            spi2: Spi2::steal(),
            sysctrl: Sysctrl::steal(),
            uart1: Uart1::steal(),
            uart2: Uart2::steal(),
            uart3: Uart3::steal(),
            vc1: Vc1::steal(),
            vc2: Vc2::steal(),
            wwdt: Wwdt::steal(),
        }
    }
}
